### ISSUE TITLE
Missing version.json file error when running simple_examples.ipynb

### ISSUE THREAD

**Issue by BobvanSchendel** [OlivierBeq/Papyrus-scripts#1]
When running the simple_examples notebook through jupyterlab I get an 'No such file or directory: '/path/to/papyrus/data/papyrus/versions.json' error.

I followed the readme, is there a file missing or did I make a mistake somewhere?

**Comment by OlivierBeq** [comment]
The notebook [simple_examples ](https://github.com/OlivierBeq/Papyrus-scripts/blob/master/notebook_examples/simple_examples.ipynb) has been updated to reflect the latest changes made to the versioning of the dataset upon automatic donwload.
