### ISSUE TITLE
openbabel cupy install

### ISSUE THREAD

**Issue by taiwanhuachenyu** [OlivierBeq/Papyrus-scripts#5]
Installation failed using pip or conda directly. 
Managed to successfully install using "conda install openbabel -c conda-forge" command.
The installation of cupy follows a similar process.
It can be installed using the command "conda install cupy -c conda-forge" in the terminal.

**Comment by OlivierBeq** [comment]
Dear @taiwanhuachenyu,

The documentation has been updated to include the `conda-forge` channel that was missing in the installation command.
Sorry for the inconvenience!
