### ISSUE TITLE
Installing, and accessing, the data from a shared location

### ISSUE THREAD

**Issue by perllaghu** [OlivierBeq/Papyrus-scripts#6]
Is there a way to install/move the data to a shared location?

Rational: I'm installing the libraries [and data] in a docker image, and then mount the individual's users home directory. This means I can't pre-install data into `~/.data/papyrus`

Is there a path I can define, or a set of paths the code will search that I can utilise?

**Comment by OlivierBeq** [comment]
We rely on [PyStow](https://github.com/cthoyt/pystow) to manage the data folder, which it sets by default to `~/.data`.
You can modify the default setting and use a custom directory by setting the `outdir` argument of the `papyrus_scripts.download.download_papyrus` to the folder you want.
The functions under `papyrus_scripts.reader` allowing access to the data all have the `source_path` argument that should correspond to the one used as `outdir` in the `papyrus_scripts.download.download_papyrus` function.
Similarly, other functions responsible of I/O have a related argument allowing this custom directory to be specified.
