### ISSUE TITLE
Descriptors data type issue

### ISSUE THREAD

**Issue by bolak92** [OlivierBeq/Papyrus-scripts#7]
Hi, 

I was trying to retrieve modred descriptors precalculated from Papyrus. 
It keeps giving me errors related to columns datatype being int instead of float and that pandas cant force it to become int.
the error message captured is
"cannot safely convert passed user dtype of int64 for float64 dtyped data in column 1169"
previously this appeared in col 1011, and col 1090.

This gets only resolved if I edit the data_types json files and change the affected cols to float.
May be there is a better way to resolve this, or include the solution in the next release.

Thanks a lot.

**Comment by OlivierBeq** [comment]
Hi Bola,
Thanks for raising the issue. If you download the version you used then (thanks to @LindeSchoenmaker) again, it should be completely gone, as should the newly released version.
