### ISSUE TITLE
download issue with scikit-learn version 1.5.2

### ISSUE THREAD

**Issue by HellevdM** [OlivierBeq/Papyrus-scripts#8]
Downloading the papyrus dataset with `papyrus download -V latest` and scikit-learn 1.5.2 (1.4.2 runs successfully) gives me the following error:

```
File "sklearn/utils/murmurhash.pyx", line 1, in init sklearn.utils.murmurhash
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by OlivierBeq** [comment]
What version of NumPy are you using?

**Comment by HellevdM** [comment]
Sorry, I can't seem to reproduce the problem now! I got this issue, then installed scikit-learn 1.4.2 and it worked. But now installing 1.5.2 again, I don't get this issue anymore. I may have mistaken the scikit-learn version I was initially using looking back, but I also don't get this error installing older sklearn versions. Not sure what happened. Apologies for the confusion
